#!/bin/bash

# test suite for arithmetic

# TODO *, / (+ rem, with divisions by 0 (at the end, obviously)), shift, etc
# TODO also have test for REAL big values, with more than 2 blocks

for X in tests/arithmetic/*.scm ; do
    echo $X
    ./p $(echo $X | sed s/\.scm$//) #| grep FAILED
    echo
done
