core-y += dispatch.c heap.c gc.c \
	primitives-list.c primitives-numeric.c \
	primitives-util.c primitives-vector.c \
	primitives-control.c

core-$(CONFIG_BIGNUM_LONG)   += bignum_long.c
core-$(CONFIG_BIGNUM_FIXED)  += bignum_fixed.c
core-$(CONFIG_DEBUG_STRINGS) += debug.c
