#lang racket

(require racket/mpair)
(require "env.rkt")

;-----------------------------------------------------------------------------

(provide make-global-env)

(define/contract (make-global-env) (-> mlist?)
  (mlist
   (make-var '#%number? #t '() '() '() #f (make-primitive 1 #f #f))
   (make-var '#%+ #t '() '() '() #f (make-primitive 2 #f #f))
   (make-var '#%- #t '() '() '() #f (make-primitive 2 #f #f))
   (make-var '#%mul-non-neg #t '() '() '() #f (make-primitive 2 #f #f))
   (make-var '#%div-non-neg #t '() '() '() #f (make-primitive 2 #f #f))
   (make-var '#%rem-non-neg #t '() '() '() #f (make-primitive 2 #f #f))
   (make-var '#%= #t '() '() '() #f (make-primitive 2 #f #f))
   (make-var '#%< #t '() '() '() #f (make-primitive 2 #f #f))
   (make-var '#%> #t '() '() '() #f (make-primitive 2 #f #f))
   (make-var '#%pair? #t '() '() '() #f (make-primitive 1 #f #f))
   (make-var '#%cons #t '() '() '() #f (make-primitive 2 #f #f))
   (make-var '#%car #t '() '() '() #f (make-primitive 1 #f #f))
   (make-var '#%cdr #t '() '() '() #f (make-primitive 1 #f #f))
   (make-var '#%set-car! #t '() '() '() #f (make-primitive 2 #f #t))
   (make-var '#%set-cdr! #t '() '() '() #f (make-primitive 2 #f #t))
   (make-var '#%null? #t '() '() '() #f (make-primitive 1 #f #f))
   (make-var '#%eq? #t '() '() '() #f (make-primitive 2 #f #f))
   (make-var '#%not #t '() '() '() #f (make-primitive 1 #f #f))
   (make-var '#%get-cont #t '() '() '() #f (make-primitive 0 #f #f))
   (make-var '#%graft-to-cont #t '() '() '() #f (make-primitive 2 #f #f))
   (make-var '#%return-to-cont #t '() '() '() #f (make-primitive 2 #f #f))
   (make-var '#%halt #t '() '() '() #f (make-primitive 0 #f #t))
   (make-var '#%symbol? #t '() '() '() #f (make-primitive 1 #f #f))
   (make-var '#%string? #t '() '() '() #f (make-primitive 1 #f #f))
   (make-var '#%string->list #t '() '() '() #f (make-primitive 1 #f #f))
   (make-var '#%list->string #t '() '() '() #f (make-primitive 1 #f #f))
   (make-var '#%make-u8vector #t '() '() '() #f (make-primitive 1 #f #f))
   (make-var '#%u8vector-ref #t '() '() '() #f (make-primitive 2 #f #f))
   (make-var '#%u8vector-set! #t '() '() '() #f (make-primitive 3 #f #t))
   (make-var '#%print #t '() '() '() #f (make-primitive 1 #f #t))
   (make-var '#%clock #t '() '() '() #f (make-primitive 0 #f #f))
   (make-var '#%motor #t '() '() '() #f (make-primitive 2 #f #t))
   (make-var '#%led #t '() '() '() #f (make-primitive 3 #f #t))
   (make-var '#%led2-color #t '() '() '() #f (make-primitive 1 #f #t))
   (make-var '#%getchar-wait #t '() '() '() #f (make-primitive 2 #f #f))
   (make-var '#%putchar #t '() '() '() #f (make-primitive 2 #f #t))
   (make-var '#%beep #t '() '() '() #f (make-primitive 2 #f #f))
   (make-var '#%adc #t '() '() '() #f (make-primitive 1 #f #f))
   (make-var '#%u8vector? #t '() '() '() #f (make-primitive 1 #f #f))
   (make-var '#%sernum #t '() '() '() #f (make-primitive 0 #f #f))
   (make-var '#%u8vector-length #t '() '() '() #f (make-primitive 1 #f #f))
   (make-var '#%boolean? #t '() '() '() #f (make-primitive 1 #f #f))
   (make-var '#%network-init #t '() '() '() #f (make-primitive 0 #f #t))
   (make-var '#%network-cleanup #t '() '() '() #f (make-primitive 0 #f #t))
   (make-var '#%receive-packet-to-u8vector #t '() '() '() #f (make-primitive 1 #f #f))
   (make-var '#%send-packet-from-u8vector #t '() '() '() #f (make-primitive 2 #f #f))
   (make-var '#%ior #t '() '() '() #f (make-primitive 2 #f #f))
   (make-var '#%xor #t '() '() '() #f (make-primitive 2 #f #f))

   (make-var '#%readyq #t '() '() '() #f #f)
   ;; TODO put in a meaningful order
   ))


;-----------------------------------------------------------------------------

(provide substitute-primitives)

;; list of primitives that can be safely substituted for the equivalent
;; function when it is called.
;; this saves the calls to the primitive wrapper functions, which are still
;; needed if a program needs the value of a "primitive", for example in :
;; (define foo car)
(define substitute-primitives
  '((number? . #%number?)
    (remainder . #%rem-non-neg)
    (= . #%=)
    (< . #%<)
    (> . #%>)
    (pair? . #%pair?)
    (cons . #%cons)
    (car . #%car)
    (cdr . #%cdr)
    (set-car! . #%set-car!)
    (set-cdr! . #%set-cdr!)
    (null? . #%null?)
    (eq? . #%eq?)
    (not . #%not)
    (modulo . #%rem-non-neg)
    (symbol? . #%symbol?)
    (string? . #%string?)
    (string->list . #%string->list)
    (list->string . #%list->string)
    (clock . #%clock)
    (beep . #%beep)
    (light . #%adc)
    (adc . #%adc)
    (sernum . #%sernum)
    (motor . #%motor)
    (led . #%led)
    (bitwise-ior . #%ior)
    (bitwise-xor . #%xor)
    (current-time . #%clock)
    (u8vector-length . #%u8vector-length)
    (u8vector-ref . #%u8vector-ref)
    (u8vector-set! . #%u8vector-set!)
    (boolean? . #%boolean?)
    (network-init . #%network-init)
    (network-cleanup . #%network-cleanup)
    (receive-packet-to-u8vector . #%receive-packet-to-u8vector)
    (send-packet-from-u8vector . #%send-packet-from-u8vector)
    ))


;-----------------------------------------------------------------------------

(provide primitive-encodings)

(define primitive-encodings
  '((#%number?                    . 0)
    (#%+                          . 1)
    (#%-                          . 2)
    (#%mul-non-neg                . 3)
    (#%div-non-neg                . 4)
    (#%rem-non-neg                . 5)
    (#%=                          . 7)
    (#%<                          . 8)
    (#%>                          . 10)
    (#%pair?                      . 12)
    (#%cons                       . 13)
    (#%car                        . 14)
    (#%cdr                        . 15)
    (#%set-car!                   . 16)
    (#%set-cdr!                   . 17)
    (#%null?                      . 18)
    (#%eq?                        . 19)
    (#%not                        . 20)
    (#%get-cont                   . 21)
    (#%graft-to-cont              . 22)
    (#%return-to-cont             . 23)
    (#%halt                       . 24)
    (#%symbol?                    . 25)
    (#%string?                    . 26)
    (#%string->list               . 27)
    (#%list->string               . 28)
    (#%make-u8vector              . 29)
    (#%u8vector-ref               . 30)
    (#%u8vector-set!              . 31)
    (#%print                      . 32)
    (#%clock                      . 33)
    (#%motor                      . 34)
    (#%led                        . 35)
    (#%led2-color                 . 36)
    (#%getchar-wait               . 37)
    (#%putchar                    . 38)
    (#%beep                       . 39)
    (#%adc                        . 40)
    (#%u8vector?                  . 41)
    (#%sernum                     . 42)
    (#%u8vector-length            . 43)
    (#%boolean?                   . 48)
    (#%network-init               . 49)
    (#%network-cleanup            . 50)
    (#%receive-packet-to-u8vector . 51)
    (#%send-packet-from-u8vector  . 52)
    (#%ior                        . 53)
    (#%xor                        . 54)))
